
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: vanpass-dev
  username: postgres
  password: <%= ENV["VANPASS_DEV_DB_PASSWORD"] %>

test:
  <<: *default
  database: vanpass-test
  username: postgres
  password: <%= ENV["VANPASS_TEST_DB_PASSWORD"] %>

production:
  <<: *default
  database: vanpass-prod
  username: postgres
  password: <%= ENV["VANPASS_PROD_DB_PASSWORD"] %>
